[alembic]
# script location
script_location = migrations
# template directory
# file_template = %%(rev)s_%%(slug)s

# timezone
# timezone = UTC

# database URL set by env.py at runtime
# sqlalchemy.url = postgresql://user:passn@host:5432/db_name

# loggers
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S