"""auto_migration

Revision ID: 4e1db24b089f
Revises: 7b58891e8319
Create Date: 2026-08-27 00:44:47.615307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e1db24b089f'
down_revision: Union[str, Sequence[str], None] = '7b58891e8319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ent_sms_config')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_media_assets_tenant_user_parent'))
        batch_op.drop_index(batch_op.f('idx_media_assets_tenant_user_type'))

    op.drop_table('media_assets')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_credit_tx_user'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_provider'), postgresql_where="((provider_order_id)::text <> ''::text)")
        batch_op.drop_index(batch_op.f('idx_payments_user'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('settings',
               existing_type=sa.String(length=255),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payments_user'), ['user_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_provider'), ['provider_order_id'], unique=False, postgresql_where="((provider_order_id)::text <> ''::text)")

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_credit_tx_user'), ['user_id', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('media_assets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('media_assets_pkey'))
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_media_assets_tenant_user_type'), ['tenant_id', 'user_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('idx_media_assets_tenant_user_parent'), ['tenant_id', 'user_id', 'parent_id'], unique=False)

    op.create_table('ent_sms_config',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('sign_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('access_key_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('secret_enc', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('code_ttl_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('send_interval_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('login_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_register', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ent_sms_config_pkey')),
    sa.UniqueConstraint('tenant_id', name=op.f('ent_sms_config_tenant_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
