"""initial_schema

Revision ID: 5d96fd6f7856
Revises: 
Create Date: 2026-08-26 23:33:59.109473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d96fd6f7856'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.BigInteger(), nullable=True),
    sa.Column('used_credits', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_models', sa.String(length=255), nullable=True),
    sa.Column('rate_limit_qps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('admin_database_backups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_mb', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_db_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dsn', sa.String(length=500), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('dbname', sa.String(length=100), nullable=True),
    sa.Column('max_open_connections', sa.Integer(), nullable=True),
    sa.Column('max_idle_connections', sa.Integer(), nullable=True),
    sa.Column('conn_max_lifetime', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_health_check', sa.String(length=255), nullable=True),
    sa.Column('avg_query_time_ms', sa.String(length=255), nullable=True),
    sa.Column('database_size_mb', sa.String(length=255), nullable=True),
    sa.Column('total_tables', sa.Integer(), nullable=True),
    sa.Column('sequential_scans', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_model_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('fallback_chain', sa.String(length=255), nullable=True),
    sa.Column('max_rpm', sa.Integer(), nullable=True),
    sa.Column('max_tpm', sa.Integer(), nullable=True),
    sa.Column('concurrent_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('input_cost_per_1m', sa.String(length=255), nullable=True),
    sa.Column('output_cost_per_1m', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_table('admin_redis_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('db_index', sa.Integer(), nullable=True),
    sa.Column('pool_size', sa.Integer(), nullable=True),
    sa.Column('min_idle_connections', sa.Integer(), nullable=True),
    sa.Column('max_conn_age', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_health_check', sa.String(length=255), nullable=True),
    sa.Column('avg_latency_ms', sa.String(length=255), nullable=True),
    sa.Column('memory_used_mb', sa.String(length=255), nullable=True),
    sa.Column('connected_clients', sa.Integer(), nullable=True),
    sa.Column('hits', sa.BigInteger(), nullable=True),
    sa.Column('misses', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('max_api_keys', sa.Integer(), nullable=True),
    sa.Column('max_models', sa.Integer(), nullable=True),
    sa.Column('monthly_quota', sa.BigInteger(), nullable=True),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('features', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('admin_workflow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=50), nullable=True),
    sa.Column('workflow_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.String(length=255), nullable=True),
    sa.Column('output_data', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('node_results', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', sa.String(length=255), nullable=True),
    sa.Column('edges', sa.String(length=255), nullable=True),
    sa.Column('error_handling_strategy', sa.String(length=20), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('published_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    op.create_table('agent_registry',
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('agent_type')
    )
    op.create_table('conversation_shares',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message_ids', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cron_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('schedule', sa.String(length=64), nullable=True),
    sa.Column('task', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.String(length=255), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('webhook_token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_catalog_installs',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('installed_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('item_id', 'tenant_id')
    )
    op.create_table('ent_catalog_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('manifest', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_group_members',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('ent_group_roles',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'role_id')
    )
    op.create_table('ent_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payload', sa.String(length=255), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_tenant_policies',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('privacy_mode', sa.Boolean(), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.Column('training_allowed', sa.Boolean(), nullable=True),
    sa.Column('redaction_rules', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('ent_user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('guest_storage',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('storage_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('storage_id')
    )
    op.create_table('llm_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_summaries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topics', sa.String(length=255), nullable=True),
    sa.Column('entities', sa.String(length=255), nullable=True),
    sa.Column('turn_start', sa.Integer(), nullable=True),
    sa.Column('turn_end', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=80), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('provider_order_id', sa.String(length=64), nullable=True),
    sa.Column('trade_no', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.String(length=255), nullable=True),
    sa.Column('expired_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('applied_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('stripe_payments',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('input', sa.String(length=255), nullable=True),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unified_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('shared_context', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_memory_profile',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('item_key', sa.String(length=128), nullable=False),
    sa.Column('item_value', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.String(length=255), nullable=True),
    sa.Column('last_referenced_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'slot', 'item_key')
    )
    op.create_table('workflow_instances',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('results', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_api_call_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=50), nullable=True),
    sa.Column('workflow_id', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('credits_consumed', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['admin_api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('dns_provider', sa.String(length=50), nullable=True),
    sa.Column('dns_record_id', sa.String(length=100), nullable=True),
    sa.Column('cname_target', sa.String(length=200), nullable=True),
    sa.Column('ssl_status', sa.String(length=20), nullable=True),
    sa.Column('ssl_expires_at', sa.String(length=255), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verified_at', sa.String(length=255), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin_tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('admin_tenant_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('stat_date', sa.String(length=255), nullable=True),
    sa.Column('api_calls', sa.BigInteger(), nullable=True),
    sa.Column('tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('credits_consumed', sa.BigInteger(), nullable=True),
    sa.Column('storage_mb', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin_tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tools', sa.String(length=255), nullable=True),
    sa.Column('llm_config', sa.String(length=255), nullable=True),
    sa.Column('max_turns', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('ssl_status', sa.String(length=16), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('ent_captcha_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('site_key', sa.String(length=256), nullable=True),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.Column('verify_url', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_oidc_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('issuer', sa.String(length=512), nullable=True),
    sa.Column('client_id', sa.String(length=256), nullable=True),
    sa.Column('client_secret_enc', sa.Text(), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_provision', sa.Boolean(), nullable=True),
    sa.Column('role_mapping', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('provider_type', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('auth_url', sa.String(length=512), nullable=True),
    sa.Column('token_url', sa.String(length=512), nullable=True),
    sa.Column('userinfo_url', sa.String(length=512), nullable=True),
    sa.Column('extra', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_quota_pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('resource_type', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.BigInteger(), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.Column('assignee', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('campaign_type', sa.String(length=32), nullable=True),
    sa.Column('config', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('participants', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('okrs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('objective', sa.String(length=255), nullable=True),
    sa.Column('key_results', sa.String(length=255), nullable=True),
    sa.Column('quarter', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('assignee', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('chunks_received', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('storage_id', sa.String(length=64), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_set', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_id')
    )
    op.create_table('wiki_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_model_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('allowed_models', sa.String(length=255), nullable=True),
    sa.Column('per_model_limits', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ent_roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_quota_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=10), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['ent_quota_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ent_user_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ent_oidc_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), nullable=True),
    sa.Column('config', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('doc_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('payload', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_graphs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('graph_json', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('billing_records')
    op.drop_table('workflow_graphs')
    op.drop_table('tasks')
    op.drop_table('sessions')
    op.drop_table('knowledge_bases')
    op.drop_table('ent_user_identities')
    op.drop_table('ent_quota_allocations')
    op.drop_table('ent_model_policies')
    op.drop_table('credit_transactions')
    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    op.drop_table('agent_sessions')
    op.drop_table('wiki_pages')
    op.drop_table('users')
    op.drop_table('uploads')
    op.drop_table('support_tickets')
    op.drop_table('okrs')
    op.drop_table('meeting_notes')
    op.drop_table('marketing_campaigns')
    op.drop_table('kb_articles')
    op.drop_table('enterprise_tasks')
    op.drop_table('ent_roles')
    op.drop_table('ent_quota_pools')
    op.drop_table('ent_oidc_providers')
    op.drop_table('ent_groups')
    op.drop_table('ent_captcha_config')
    op.drop_table('domains')
    op.drop_table('agents')
    op.drop_table('admin_tenant_usage')
    op.drop_table('admin_domains')
    op.drop_table('admin_api_call_logs')
    op.drop_table('workflow_instances')
    op.drop_table('user_memory_profile')
    op.drop_table('unified_sessions')
    op.drop_table('tool_calls')
    op.drop_table('tenants')
    op.drop_table('system_settings')
    op.drop_table('stripe_payments')
    op.drop_table('schema_migrations')
    op.drop_table('payments')
    op.drop_table('memory_summaries')
    op.drop_table('llm_models')
    op.drop_table('guest_storage')
    op.drop_table('ent_user_roles')
    op.drop_table('ent_tenant_policies')
    op.drop_table('ent_templates')
    op.drop_table('ent_group_roles')
    op.drop_table('ent_group_members')
    op.drop_table('ent_catalog_items')
    op.drop_table('ent_catalog_installs')
    op.drop_table('cron_jobs')
    op.drop_table('conversation_shares')
    op.drop_table('agent_registry')
    op.drop_table('admin_workflows')
    op.drop_table('admin_workflow_executions')
    op.drop_table('admin_tenants')
    op.drop_table('admin_redis_configs')
    op.drop_table('admin_model_configs')
    op.drop_table('admin_db_configs')
    op.drop_table('admin_database_backups')
    op.drop_table('admin_api_keys')
    # ### end Alembic commands ###
