"""auto_migration

Revision ID: 7b58891e8319
Revises: 78a15f2c38aa
Create Date: 2026-08-27 00:30:16.198085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b58891e8319'
down_revision: Union[str, Sequence[str], None] = '78a15f2c38aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_credit_tx_user'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_provider'), postgresql_where="((provider_order_id)::text <> ''::text)")
        batch_op.drop_index(batch_op.f('idx_payments_user'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payments_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_provider'), ['provider_order_id'], unique=False, postgresql_where="((provider_order_id)::text <> ''::text)")

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_credit_tx_user'), ['user_id'], unique=False)

    # ### end Alembic commands ###
