"""add media_assets table

Revision ID: a1b2c3d4e5f6
Revises: 2206deae576b
Create Date: 2026-08-26 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '2206deae576b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('tenant_id', sa.String(36), sa.ForeignKey('tenants.id')),
        sa.Column('user_id', sa.String(36), nullable=True),
        sa.Column('type', sa.String(16), server_default='text'),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('file_url', sa.String(1024), server_default=''),
        sa.Column('file_path', sa.String(512), server_default=''),
        sa.Column('mime_type', sa.String(64), server_default=''),
        sa.Column('thumbnail', sa.String(512), server_default=''),
        sa.Column('metadata', sa.String(255), server_default='{}'),
        sa.Column('tags', sa.String(255), server_default='[]'),
        sa.Column('category', sa.String(64), server_default=''),
        sa.Column('size', sa.BigInteger, server_default='0'),
        sa.Column('created_at', sa.String(255), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.String(255), server_default=sa.text('now()')),
        sa.Column('parent_id', sa.String(64), server_default=''),
    )
    
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index('idx_media_assets_tenant_user', ['tenant_id', 'user_id'])
        batch_op.create_index('idx_media_assets_parent', ['parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index('idx_media_assets_parent')
        batch_op.drop_index('idx_media_assets_tenant_user')
    
    op.drop_table('media_assets')
    # ### end Alembic commands ###
