"""auto_migration

Revision ID: b679e9264f86
Revises: 3e447730490a
Create Date: 2026-08-27 11:09:48.158587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b679e9264f86'
down_revision: Union[str, Sequence[str], None] = '3e447730490a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_credit_tx_user'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_provider'), postgresql_where="((provider_order_id)::text <> ''::text)")
        batch_op.drop_index(batch_op.f('idx_payments_user'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payments_user'), ['user_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_provider'), ['provider_order_id'], unique=False, postgresql_where="((provider_order_id)::text <> ''::text)")

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_credit_tx_user'), ['user_id', sa.literal_column('created_at DESC')], unique=False)

    # ### end Alembic commands ###
