"""
SQLAlchemy 模型包 - 由代码生成器自动生成
所有模型统一继承 Base，由 Alembic 自动发现
"""

from .base import Base

# _LAZY_IMPORTS 字典由代码生成器维护，用于 Alembic 自动发现模型
# 格式: {ModelName: .module_path}
_LAZY_IMPORTS = {
    'AdminApiCallLog': '.admin_api_call_log',
    'AdminApiKey': '.admin_api_key',
    'AdminCronJob': '.admin_cron_job',
    'AdminDatabaseBackup': '.admin_database_backup',
    'AdminDbConfig': '.admin_db_config',
    'AdminDomain': '.admin_domain',
    'AdminModelConfig': '.admin_model_config',
    'AdminRedisConfig': '.admin_redis_config',
    'AdminTenant': '.admin_tenant',
    'AdminTenantUsage': '.admin_tenant_usage',
    'AdminWorkflow': '.admin_workflow',
    'AdminWorkflowExecution': '.admin_workflow_execution',
    'Agent': '.agent',
    'AgentRegistry': '.agent_registry',
    'AgentSession': '.agent_session',
    'ApiKey': '.api_key',
    'AuditLog': '.audit_log',
    'BillingRecord': '.billing_record',
    'ConversationShare': '.conversation_share',
    'CreditTransaction': '.credit_transaction',
    'CronJob': '.cron_job',
    'Domain': '.domain',
    'EntCaptchaConfig': '.ent_captcha_config',
    'EntCatalogInstall': '.ent_catalog_install',
    'EntCatalogItem': '.ent_catalog_item',
    'EntGroup': '.ent_group',
    'EntGroupMember': '.ent_group_member',
    'EntGroupRole': '.ent_group_role',
    'EntModelPolicy': '.ent_model_policy',
    'EntOidcProvider': '.ent_oidc_provider',
    'EntQuotaAllocation': '.ent_quota_allocation',
    'EntQuotaPool': '.ent_quota_pool',
    'EntRole': '.ent_role',
    'EntTemplate': '.ent_template',
    'EntTenantPolicy': '.ent_tenant_policy',
    'EntUserIdentity': '.ent_user_identity',
    'EntUserRole': '.ent_user_role',
    'EnterpriseTask': '.enterprise_task',
    'GuestStorage': '.guest_storage',
    'KbArticle': '.kb_article',
    'KnowledgeBase': '.knowledge_base',
    'KnowledgeChunk': '.knowledge_chunk',
    'KnowledgeDocument': '.knowledge_document',
    'LlmModel': '.llm_model',
    'MarketingCampaign': '.marketing_campaign',
    'MediaAsset': '.media_asset',
    'MeetingNote': '.meeting_note',
    'MemorySummary': '.memory_summary',
    'Message': '.message',
    'Okr': '.okr',
    'Payment': '.payment',
    'Session': '.session',
    'StripePayment': '.stripe_payment',
    'SubagentRun': '.subagent_run',
    'SubagentRunStep': '.subagent_run_step',
    'SupportTicket': '.support_ticket',
    'SystemSetting': '.system_setting',
    'Task': '.task',
    'Tenant': '.tenant',
    'ToolCall': '.tool_call',
    'Turn': '.turn',
    'UnifiedMessage': '.unified_message',
    'UnifiedSession': '.unified_session',
    'Upload': '.upload',
    'User': '.user',
    'UserMemoryProfile': '.user_memory_profile',
    'WikiPage': '.wiki_page',
    'WorkflowGraph': '.workflow_graph',
    'WorkflowInstance': '.workflow_instance',
}
