package db

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// versionLock 表示 version.lock 文件的结构
type versionLock struct {
	Chiron string `json:"chiron"`
	DB     string `json:"db"`
	Python string `json:"python"`
	Go     string `json:"go"`
	Date   string `json:"date"`
}

// getLockDBRevision 从 data/version.lock 文件中读取 db revision
func getLockDBRevision() (string, error) {
	data, err := os.ReadFile("data/version.lock")
	if err != nil {
		return "", fmt.Errorf("failed to read version.lock: %w", err)
	}

	var lock versionLock
	if err := json.Unmarshal(data, &lock); err != nil {
		return "", fmt.Errorf("failed to parse version.lock: %w", err)
	}

	if lock.DB == "" {
		return "", fmt.Errorf("db revision not found in version.lock")
	}

	return lock.DB, nil
}

// getCurrentDBRevision 执行 alembic current 命令获取当前数据库的 revision
func getCurrentDBRevision(python string) (string, error) {
	cmd := exec.Command(python, "-m", "alembic", "--config", "alembic.ini", "current")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("alembic current failed: %w, output: %s", err, string(output))
	}

	// 解析输出，格式类似: "62dee11343df (head)"
	outputStr := strings.TrimSpace(string(output))
	if outputStr == "" {
		return "", fmt.Errorf("alembic current returned empty output")
	}

	// 提取 revision ID（第一个空格前的部分）
	parts := strings.Fields(outputStr)
	if len(parts) == 0 {
		return "", fmt.Errorf("failed to parse alembic current output: %s", outputStr)
	}

	return parts[0], nil
}

// RunMigrations 执行 Alembic 数据库迁移（alembic upgrade head）
// dsn 为 PostgreSQL 连接串，通过环境变量 DATABASE_DSN 传递给 Alembic
func RunMigrations(dsn string) error {
	dsn = strings.Replace(dsn, "postgres://", "postgresql://", 1)
	os.Setenv("DATABASE_DSN", dsn)
	// 确保 APP_SECRET 已写入 .env 供 Alembic 使用
	if appSecret := os.Getenv("APP_SECRET"); appSecret != "" {
		content := fmt.Sprintf("# Generated by install wizard\nAPP_SECRET=%s\n", appSecret)
		os.WriteFile(".env", []byte(content), 0o600)
	}
	os.Setenv("PYTHONUTF8", "1")
	python := "python"
	if v := os.Getenv("PYTHON"); v != "" {
		python = v
	} else if v := os.Getenv("CHIRON_PYTHON"); v != "" {
		python = v
	}

	// Step 1: 检查 version.lock 中的 revision 是否与数据库一致
	lockRevision, err := getLockDBRevision()
	if err != nil {
		return fmt.Errorf("failed to read version.lock: %w", err)
	}

	currentRevision, err := getCurrentDBRevision(python)
	if err != nil {
		return fmt.Errorf("failed to get current db revision: %w", err)
	}

	// 如果 revision 一致，跳过迁移生成和执行
	if lockRevision == currentRevision {
		fmt.Printf("Database is already at revision %s, skipping migration\n", currentRevision)
		return nil
	}

	// Step 2: 版本不一致时，自动生成迁移脚本
	versionDescribe := fmt.Sprintf("db_%s", lockRevision)
	revisionCmd := exec.Command(python, "-m", "alembic", "--config", "alembic.ini",
		"revision", "--autogenerate", "-m", versionDescribe)
	revisionCmd.Dir = "."
	revisionCmd.Stdout = os.Stdout
	revisionCmd.Stderr = os.Stderr
	_ = revisionCmd.Run() // 忽略错误（空迁移会报错，不影响）

	// Step 3: 执行迁移
	runCmd := exec.Command(python, "-m", "alembic", "--config", "alembic.ini", "upgrade", "head")
	runCmd.Dir = "."
	runCmd.Stdout = os.Stdout
	runCmd.Stderr = os.Stderr

	if err := runCmd.Run(); err != nil {
		return fmt.Errorf("alembic migration failed: %w", err)
	}

	return nil
}
