package db

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// versionLock represents the data/version.lock file
type versionLock struct {
	DB string `json:"db"`
}

// getExpectedRevision reads the expected db revision from data/version.lock
func getExpectedRevision() (string, error) {
	data, err := os.ReadFile("data/version.lock")
	if err != nil {
		return "", err
	}
	var lock versionLock
	if err := json.Unmarshal(data, &lock); err != nil {
		return "", err
	}
	return lock.DB, nil
}

// getCurrentRevision runs "alembic current" to get the database's actual revision
func getCurrentRevision(python string) (string, error) {
	cmd := exec.Command(python, "-m", "alembic", "--config", "alembic.ini", "current")
	cmd.Dir = "."
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("alembic current failed: %w: %s", err, string(output))
	}
	// Output format: "xxx (head)" - extract revision ID
	trimmed := strings.TrimSpace(string(output))
	parts := strings.Fields(trimmed)
	if len(parts) == 0 {
		return "", fmt.Errorf("alembic current returned empty output")
	}
	return parts[0], nil
}

// updateVersionLockDB updates data/version.lock with the given revision
func updateVersionLockDB(revision string) error {
	lock := versionLock{DB: revision}
	data, err := json.MarshalIndent(lock, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile("data/version.lock", data, 0o644)
}

// listMigrationFiles returns a list of migration file names in the given directory
func listMigrationFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".py") {
			files = append(files, e.Name())
		}
	}
	return files, nil
}

// findNewFile returns the first file in after that is not in before
func findNewFile(before, after []string) string {
	beforeSet := make(map[string]bool)
	for _, f := range before {
		beforeSet[f] = true
	}
	for _, f := range after {
		if !beforeSet[f] {
			return f
		}
	}
	return ""
}

// isEmptyMigration checks if a migration file contains only empty upgrade/downgrade
func isEmptyMigration(filePath string) (bool, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return false, err
	}
	// Simple heuristic: if the file does not contain "op." it's probably empty
	// Better: check for "pass" in upgrade/downgrade functions
	content := string(data)
	// Look for typical empty migration patterns
	if strings.Contains(content, "def upgrade():\n    pass") &&
		strings.Contains(content, "def downgrade():\n    pass") {
		return true, nil
	}
	// Also check if there are no operations
	if !strings.Contains(content, "op.") {
		return true, nil
	}
	return false, nil
}

// RunMigrations 执行 Alembic 数据库迁移（alembic upgrade head）
// dsn 为 PostgreSQL 连接串，通过环境变量 DATABASE_DSN 传递给 Alembic
func RunMigrations(dsn string) error {
	// Normalize DSN: postgres:// -> postgresql:// for Alembic
	dsn = strings.Replace(dsn, "postgres://", "postgresql://", 1)
	os.Setenv("DATABASE_DSN", dsn)

	// Ensure APP_SECRET is written to .env for Alembic
	// Preserve other configuration entries (e.g., DATABASE_DSN) in the file.
	if appSecret := os.Getenv("APP_SECRET"); appSecret != "" {
		var existingLines []string
		if data, err := os.ReadFile(".env"); err == nil {
			lines := strings.Split(string(data), "\n")
			for _, line := range lines {
				// Skip old APP_SECRET line and comment header
				if strings.HasPrefix(line, "APP_SECRET=") || line == "# Generated by install wizard" {
					continue
				}
				if strings.TrimSpace(line) != "" {
					existingLines = append(existingLines, line)
				}
			}
		}

		// Build new .env content
		var content strings.Builder
		content.WriteString("# Generated by install wizard\n")
		content.WriteString(fmt.Sprintf("APP_SECRET=%s\n", appSecret))

		// Append other existing configurations
		for _, line := range existingLines {
			content.WriteString(line + "\n")
		}

		if err := os.WriteFile(".env", []byte(content.String()), 0o600); err != nil {
			return fmt.Errorf("failed to write .env: %w", err)
		}
	}

	os.Setenv("PYTHONUTF8", "1")
	python := "python"
	if v := os.Getenv("PYTHON"); v != "" {
		python = v
	} else if v := os.Getenv("CHIRON_PYTHON"); v != "" {
		python = v
	}

	// Step 1: Check version consistency
	expected, err := getExpectedRevision()
	if err != nil {
		// version.lock may not exist yet; that's okay, we'll generate migration
		fmt.Printf("No version.lock found, will generate initial migration\n")
	} else {
		current, err := getCurrentRevision(python)
		if err == nil && current == expected {
			fmt.Printf("Database revision matches version.lock (%s), no migration needed\n", expected)
			return nil
		}
		if err != nil {
			fmt.Printf("Failed to get current revision, generating migration: %v\n", err)
		} else {
			fmt.Printf("Version mismatch: lock=%s, db=%s, generating migration\n", expected, current)
		}
	}

	// Step 2: Generate migration if needed
	migrationsDir := filepath.Join(".", "migrations", "versions")
	beforeFiles, _ := listMigrationFiles(migrationsDir)

	revisionMsg := "auto_migration"
	if expected != "" {
		revisionMsg = fmt.Sprintf("db_%s", expected)
	}
	revisionCmd := exec.Command(python, "-m", "alembic", "--config", "alembic.ini",
		"revision", "--autogenerate", "-m", revisionMsg)
	revisionCmd.Dir = "."
	revisionCmd.Stdout = os.Stdout
	revisionCmd.Stderr = os.Stderr
	_ = revisionCmd.Run() // Ignore error; empty migration may cause error but we continue

	// Check if a new migration file was generated
	afterFiles, _ := listMigrationFiles(migrationsDir)
	newFile := findNewFile(beforeFiles, afterFiles)

	if newFile == "" {
		// No new file generated, models match database
		fmt.Printf("No migration generated, models match database\n")
		// Update version.lock to current database revision
		current, err := getCurrentRevision(python)
		if err != nil {
			return fmt.Errorf("failed to get current revision after no migration: %w", err)
		}
		if err := updateVersionLockDB(current); err != nil {
			fmt.Printf("Warning: failed to update version.lock: %v\n", err)
		}
		return nil
	}

	// Check if the new migration is empty
	isEmpty, err := isEmptyMigration(filepath.Join(migrationsDir, newFile))
	if err != nil {
		fmt.Printf("Warning: failed to check migration file: %v\n", err)
		// Continue anyway
	}

	if isEmpty {
		// Empty migration, remove it and update version.lock
		if err := os.Remove(filepath.Join(migrationsDir, newFile)); err != nil {
			fmt.Printf("Warning: failed to remove empty migration: %v\n", err)
		}
		fmt.Printf("Empty migration removed, updating version.lock\n")
		current, err := getCurrentRevision(python)
		if err != nil {
			return fmt.Errorf("failed to get current revision after removing empty migration: %w", err)
		}
		if err := updateVersionLockDB(current); err != nil {
			fmt.Printf("Warning: failed to update version.lock: %v\n", err)
		}
		return nil
	}

	// Step 3: Apply the generated migration
	fmt.Printf("Applying new migration: %s\n", newFile)
	upgradeCmd := exec.Command(python, "-m", "alembic", "--config", "alembic.ini", "upgrade", "head")
	upgradeCmd.Dir = "."
	upgradeCmd.Stdout = os.Stdout
	upgradeCmd.Stderr = os.Stderr

	if err := upgradeCmd.Run(); err != nil {
		return fmt.Errorf("alembic upgrade after migration failed: %w", err)
	}

	// Step 4: Update version.lock to the new current revision
	current, err := getCurrentRevision(python)
	if err != nil {
		return fmt.Errorf("failed to get current revision after upgrade: %w", err)
	}
	if err := updateVersionLockDB(current); err != nil {
		fmt.Printf("Warning: failed to update version.lock: %v\n", err)
	}

	fmt.Printf("Migration completed successfully\n")
	return nil
}
