package db

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// RunMigrations 执行 Alembic 数据库迁移（alembic upgrade head）
// dsn 为 PostgreSQL 连接串，通过环境变量 DATABASE_DSN 传递给 Alembic
func RunMigrations(dsn string) error {
	dsn = strings.Replace(dsn, "postgres://", "postgresql://", 1)
	os.Setenv("DATABASE_DSN", dsn)
	// 确保 APP_SECRET 已写入 .env 供 Alembic 使用
    if appSecret := os.Getenv("APP_SECRET"); appSecret != "" {
	    content := fmt.Sprintf("# Generated by install wizard\nAPP_SECRET=%s\n", appSecret)
	    os.WriteFile(".env", []byte(content), 0o600)
    }
	os.Setenv("PYTHONUTF8", "1")
	python := "python"
	if v := os.Getenv("PYTHON"); v != "" {
		python = v
	} else if v := os.Getenv("CHIRON_PYTHON"); v != "" {
		python = v
	}

	// Step 1: 自动生成迁移脚本（如果无变更会失败，忽略）
	revisionCmd := exec.Command(python, "-m", "alembic", "--config", "alembic.ini",
		"revision", "--autogenerate", "-m", "auto")
	revisionCmd.Dir = "."
	revisionCmd.Stdout = os.Stdout
	revisionCmd.Stderr = os.Stderr
	_ = revisionCmd.Run() // 忽略错误（空迁移会报错，不影响）

	// Step 2: 执行迁移
	runCmd := exec.Command(python, "-m", "alembic", "--config", "alembic.ini", "upgrade", "head")
	runCmd.Dir = "."
	runCmd.Stdout = os.Stdout
	runCmd.Stderr = os.Stderr

	if err := runCmd.Run(); err != nil {
		return fmt.Errorf("alembic migration failed: %w", err)
	}

	return nil
}
